(() => {
 const esc=(v)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
 const asText=(d)=>Object.entries(d).map(([k,v])=>`${k}: ${v??""}`).join("\n");
 async function copy(text,b){try{await navigator.clipboard.writeText(text);const o=b.textContent;b.textContent="Copied";setTimeout(()=>b.textContent=o,1500)}catch{window.prompt("Copy this information:",text)}}
 function draft(){try{return JSON.parse(localStorage.getItem("imaginable_pending_customer")||"null")}catch{return null}}
 function renderDraft(){const d=draft(),root=document.getElementById("draftPanel");if(!d){root.hidden=true;return}root.hidden=false;root.innerHTML=`<strong>Customer draft ready from Job ${esc(d.latest_job_number||"")}</strong><p>${esc(d.name)} · ${esc(d.favorite_product||"")}</p><div class="actions"><button class="button" id="copyCustomer">Copy customer fields</button><a class="button secondary" href="https://app.pagescms.org" rel="noopener">Open Customer Hub CMS</a><button class="button secondary" id="clearCustomer">Clear</button></div>`;document.getElementById("copyCustomer").onclick=e=>copy(asText(d),e.currentTarget);document.getElementById("clearCustomer").onclick=()=>{localStorage.removeItem("imaginable_pending_customer");renderDraft()}}
 async function load(){renderDraft();try{const r=await fetch("../data/customers.json",{cache:"no-store"});if(!r.ok)throw 0;const customers=(await r.json()).customers||[];const active=customers.filter(c=>c.visible!==false);document.getElementById("customers").innerHTML=active.length?active.map(c=>`<article class="card"><h3>${esc(c.name||"Unnamed customer")}</h3><span class="company">${esc(c.company||c.customer_id||"")}</span><div class="meta"><div><span>Phone</span><strong>${esc(c.phone||"—")}</strong></div><div><span>Email</span><strong>${esc(c.email||"—")}</strong></div><div><span>Total orders</span><strong>${esc(c.total_orders||1)}</strong></div><div><span>Latest job</span><strong>${esc(c.latest_job_number||"—")}</strong></div><div><span>Favorite product</span><strong>${esc(c.favorite_product||"—")}</strong></div><div><span>Technique</span><strong>${esc(c.preferred_technique||"—")}</strong></div></div><div class="actions"><a class="button" href="https://app.pagescms.org" rel="noopener">Manage customer</a></div></article>`).join(""):'<div class="empty">No customers saved yet.</div>'}catch(e){document.getElementById("customers").innerHTML='<div class="empty">Could not load Customer Hub data.</div>'}}
 load();
})();
